name: doge-action
description: "test action written in GO"
author: kuritka
# see: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: grid
  color: red
inputs:
  cluster-name:
    description: "(Required) Cluster name."
    required: true

runs:
  using: composite
  steps:
    - id: main
      shell: bash
      run: |
        cd ${{ github.action_path }}
        go mod tidy
        go run main.go
      env:
        CLUSTER_NAME: ${{ inputs.cluster-name }}
#      run: cd ${{ github.action_path }} && go mod tidy && go run main.go
#      env:
#        CLUSTER_NAME: ${{ inputs.cluster-name }}
